# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: octo.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'octo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nocto.proto\x12\x04Octo\"e\n\x03Url\x12\x10\n\x08revision\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x1e\n\x05state\x18\x03 \x01(\x0e\x32\x0f.Octo.Url.State\"\x1f\n\x05State\x12\x06\n\x02_0\x10\x00\x12\x06\n\x02_1\x10\x01\x12\x06\n\x02_2\x10\x02\"!\n\x07UrlList\x12\x16\n\x03url\x18\x01 \x03(\x0b\x32\t.Octo.Url\"\xa4\x02\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\x0b\n\x03\x63rc\x18\x05 \x01(\r\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12\r\n\x05tagId\x18\x07 \x03(\x05\x12\x14\n\x0c\x64\x65pendencies\x18\x08 \x03(\x05\x12\x1f\n\x05state\x18\t \x01(\x0e\x32\x10.Octo.Data.State\x12\x0b\n\x03md5\x18\n \x01(\t\x12\x12\n\nobjectName\x18\x0b \x01(\t\x12\x12\n\ngeneration\x18\x0c \x01(\x04\x12\x17\n\x0fuploadVersionId\x18\r \x01(\x05\"/\n\x05State\x12\x06\n\x02_0\x10\x00\x12\x06\n\x02_1\x10\x01\x12\x06\n\x02_2\x10\x02\x12\x06\n\x02_3\x10\x03\x12\x06\n\x02_4\x10\x04\"\x87\x01\n\x08\x44\x61tabase\x12\x10\n\x08revision\x18\x01 \x01(\x05\x12#\n\x0f\x61ssetBundleList\x18\x02 \x03(\x0b\x32\n.Octo.Data\x12\x0f\n\x07tagname\x18\x03 \x03(\t\x12 \n\x0cresourceList\x18\x04 \x03(\x0b\x32\n.Octo.Data\x12\x11\n\turlFormat\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'octo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URL']._serialized_start=20
  _globals['_URL']._serialized_end=121
  _globals['_URL_STATE']._serialized_start=90
  _globals['_URL_STATE']._serialized_end=121
  _globals['_URLLIST']._serialized_start=123
  _globals['_URLLIST']._serialized_end=156
  _globals['_DATA']._serialized_start=159
  _globals['_DATA']._serialized_end=451
  _globals['_DATA_STATE']._serialized_start=404
  _globals['_DATA_STATE']._serialized_end=451
  _globals['_DATABASE']._serialized_start=454
  _globals['_DATABASE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
